positive_keywords:
  - 喜欢
  - 爱
  - 爱你
  - 想你
  - 可爱
  - 温柔
  - 贴心
  - 懂我
  - 靠谱
  - 谢谢
  - 感谢
  - 辛苦了
  - 加油
  - 支持你
  - 真棒
  - 太棒了
  - 厉害
  - 优秀
  - 赞
  - 牛
  - 完美
  - 舒服
  - 开心
  - 高兴
  - 快乐
  - 满意
  - 感动
  - 欣赏你
  - 佩服
  - 崇拜

negative_keywords:
  - 讨厌
  - 反感
  - 厌恶
  - 恶心
  - 烦
  - 烦死
  - 烦死了
  - 烦躁
  - 无语
  - 真无语
  - 离谱
  - 真离谱
  - 离大谱
  - 呵呵
  - 呵呵哒
  - 算了
  - 随便你
  - 随你便
  - 你开心就好
  - 没意思
  - 无聊
  - 幼稚
  - 别烦
  - 别烦我
  - 别来
  - 别搞
  - 别闹
  - 别打扰
  - 别打扰我
  - 离我远点
  - 离远点
  - 别靠近
  - 少来
  - 不想理你
  - 懒得理
  - 不想听
  - 我不想听
  - 别说了
  - 别再说了
  - 闭嘴
  - 滚
  - 滚开
  - 滚蛋
  - 滚远点
  - 生气
  - 恼火
  - 失望
  - 受够了
  - 受不了了
  - 够了
  - 不好
  - 草泥马
  - 草尼玛

strong_negative_patterns:
  - (操|艹|草|槽).{0,3}(你|尼|拟|伱|泥).{0,3}(妈|马|玛)
  - (干|艹|草).{0,3}(你|尼|拟|伱|泥).{0,3}(妈|马|玛)
  - (妈|马).{0,3}(逼|b)
  - c\\s*n\\s*m
  - cao\\s*ni\\s*ma
  - 草(泥|尼)玛
